name: Generate POT file
on:
    push:
        branches:
            - stable

jobs:
    WP_Generate_POT_File:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: WP POT Generator
              uses: h1dd3nsn1p3r/action-wordpress-pot-generator@main
              with:
                  destination_path: "./languages"
                  slug: "orchid-store"
                  text_domain: "orchid-store"
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
